#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by git-commit with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

exec < /dev/tty

test "" != "$(grep 'EX-' "$1")" || {
	echo "Commit message is missing JIRA issue number. Do you still want to commit? (y/n)"

	read answer

	case $answer in 
		"y" )
		exit 0
		;;	
		"Y" )
		exit 0
		;;

	esac

	echo >&2 "ERROR: Commit message is missing Jira issue number."
	exit 1
}
