#!/bin/bash
export EDITOR=vim
export ANT_HOME=/opt/ant
#export ATLAS_SDK=/opt/atlas-sdk
#export M2_HOME=/opt/maven
#export M3_HOME=/opt/m3 
export MAVEN_COLOR=true 
export MAVEN_OPTS=-Xmx2G 

export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/
export PATH=$M2_HOME/bin:$M3_HOME/bin:$PATH:$ANT_HOME/bin:$JAVA_HOME/bin
if [[ -s /Volumes/Data/Users/colin/.rvm/scripts/rvm ]] ; then source /Volumes/Data/Users/colin/.rvm/scripts/rvm ; fi

export GDAL=/Library/Frameworks/GDAL.framework/Versions/Current/Programs
export PSQL=/Applications/Postgres93.app/Contents/MacOS/bin/

# Hack so homebrew is happy
export PATH=$PSQL:/usr/local/bin:$PATH:$GDAL
export PROJSO=/Library/Frameworks/PROJ.framework/PROJ
#export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH

export ANDROID_SDK=/usr/local/share/android-sdk/tools

export PATH=$PATH:$ANDROID_SDK/bin

enter_directory() {
if [[ $PWD == $PREV_PWD ]]; then
    return
fi

PREV_PWD=$PWD
if [[ -f ".nvmrc" ]]; then
    nvm use
    NVM_DIRTY=true
elif [[ $NVM_DIRTY = true ]]; then
    nvm use default
    NVM_DIRTY=false
fi
}

export PROMPT_COMMAND=enter_directory
